[[model]]
name = "grok-code-fast-1-openrouter"
provider = "openrouter"
model_id = "x-ai/grok-code-fast-1"
shortcut = "nitro"

[[model]]
name = "glm-5-openrouter"
provider = "openrouter"
model_id = "z-ai/glm-5"
shortcut = "nitro"

[[model]]
name = "glm-4.7-openrouter"
provider = "openrouter"
model_id = "z-ai/glm-4.7"
shortcut = "nitro"

[[model]]
name = "glm-4.7-flash-openrouter"
provider = "openrouter"
model_id = "z-ai/glm-4.7-flash"
shortcut = "nitro"

[[model]]
name = "minimax-m2.5-openrouter"
provider = "openrouter"
model_id = "minimax/minimax-m2.5"
shortcut = "nitro"

[[model]]
name = "glm-4.7"
provider = "zai-coding-plan"
model_id = "glm-4.7"